CC=gcc
CFLAGS=-Wall -std=c99
CCLINK=-framework Cocoa -ljpeg -lglfw -framework OpenGL
SOURCES=display.c util.c generate.c population.c
OUTPUT = opengl-ga

all: $(OUTPUT)

$(OUTPUT): $(SOURCES)
	$(CC) $(CFLAGS) $(CCLINK) $(SOURCES) -o $(OUTPUT)

clean:
	rm -f *.o $(OUTPUT)
